apiVersion: v1
kind: Secret
metadata:
  name: piggymetrics
type: Opaque
data:  #Replace default values. This is only meant to create the structure.
  config_service_password: password
  auth_mongodb_password: password
  notification_service_password: password
  notification_mongodb_password: password
  statistics_service_password: password
  statistics_mongodb_password: password
  account_service_password: password
  account_mongodb_password: password
  notification_email_host: c210cC5nbWFpbC5jb20=
  notification_email_port: NDY1
  notification_email_user: ZGV2LXVzZXI=
  notification_email_pass: ZGV2LXBhc3N3b3Jk