kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app:  rabbitmq
  ports:
    - port: 15672
      targetPort: 15672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels: 
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: Always
        ports:
          - containerPort: 15672