kind: Service
apiVersion: v1
metadata:
  name: statistics-service-svc
  labels:
    app: statistics-service
spec:
  selector:
    app:  statistics-service
  ports:
  - port: 7000
    # protocol: TCP
    targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
  labels: 
    app: statistics-service
spec:
  selector:
    matchLabels:
      app: statistics-service
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
      - name: statistics-service
        image: clintoncao/ms_pgm_statistics_svc
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: statistics_mongodb_password
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: statistics_service_password
        imagePullPolicy: Always
        ports:
          - containerPort: 7000