apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_service_address: http://config-0.config.default.svc.cluster.local:8888
---

kind: Service
apiVersion: v1
metadata:
  name: config-svc
  labels:
    app: config
spec:
  clusterIP: None
  selector:
    app:  config
  ports:
    - port: 8888
      targetPort: 8888
      name: config

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config
spec:
  serviceName: "config"
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: clintoncao/ms_pgm_config
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_server_address
        imagePullPolicy: Always
        ports:
          - containerPort: 8888

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: config-svc-np
#   labels: 
#     app: config
# spec:
#   type: NodePort
#   selector:
#     app:  config
#   ports:
#     - port: 8888
#       targetPort: 8888
#       nodePort: 8888