apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cm
data:
  eureka_service_address: http://registry-0.registry.default.svc.cluster.local:8761/eureka/
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: "registry"
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: clintoncao/ms_pgm_registry
        imagePullPolicy: Always
        ports:
          - containerPort: 8761
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: registry-cm
                key: eureka_service_address
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: piggymetrics
                key: config_service_password
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  labels:
    app: registry
spec:
  clusterIP: None
  ports:
    - port: 8761
      targetPort: 8761
      name: registry
  selector:
    app: registry

---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc-np
  labels:
    app: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 80
      targetPort: 8761
      nodePort: 31201
