kind: Service
apiVersion: v1
metadata:
  name: gateway-svc-np
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app:  gateway
  ports:
  - port: 4000
    # protocol: TCP
    targetPort: 4000
    nodePort: 31101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels: 
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: clintoncao/ms_pgm_gateway
        imagePullPolicy: Always
        ports:
          - containerPort: 4000