kind: Service
apiVersion: v1
metadata:
  name: account-service-svc
  labels:
    app: account-service
spec:
  selector:
    app:  account-service
  ports:
  - port: 6000
    # protocol: TCP
    targetPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels: 
    app: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: clintoncao/ms_pgm_account_svc
        env:
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_service_password
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_mongodb_password
        imagePullPolicy: Always
        ports:
          - containerPort: 6000